### ISSUE TITLE
It would be good if authors can share configurations on other datasets.

### ISSUE THREAD

**Issue by MrAxios** [ChunjingXiao/DiffAD#2]
Nice work! However, authors only share their configurations on SMAP and PSM, and they have different settings such as 'l_resolution' and 'r_resolution'. It seems that those differences are not mentioned in the paper. We have tried to reproduce the results on SMD but failed. It would be very helpful if authors can share their settings on SMD, MSL, and SWAT so that we can reproduce the results much more accurately.

**Comment by ZehuaGou** [comment]
We have uploaded the configuration files related to the MSL and SMD datasets. However, we apologize that there are copyright restrictions related to the SWaT dataset, so we cannot provide it directly. You can find information on how to download the SWaT dataset at [SWaT](https://ieeexplore.ieee.org/abstract/document/7469060).

**Comment by MrAxios** [comment]
Thank you for sharing the configurations. It helps a lot!
